id: P006915
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W23690
  title: གསང་འདུས་བཞི་སྦྲགས་མ
  author: ''
  volumes:
    d67820b5f0a94c9891076984838de006:
      image_group_id: I2474
      title: ''
      volume_number: 1
      total_pages: 956
      base_file: v001.txt
